name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  build-and-upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cargo build --release --verbose
      - name: Upload
        run: |
          suffix=$(basename ${{ github.ref }}).${{ matrix.os }}
          zip glim.${suffix}.zip --junk-paths target/release/glim
          ./.github/workflows/upload_asset.sh glim.${suffix}.zip $GITHUB_TOKEN
